### ISSUE TITLE
Peer-to-peer review - Spec tests

### ISSUE THREAD

**Issue by vieiramanda11** [vieiramanda11/facebook-clone#8]

**Comment by ansaryergesh** [comment]
very clear testing code:)

**Comment by AndresFMoya** [comment]
Great tests Amanda! Just a suggestion that I just received. It's better to use `let` instead `before(:each)`, so the variable only loads when it is used the first time in the test and get cached until that specific test is finished. Check the following resource 🙂:
http://www.betterspecs.org/#let

**Comment by AndresFMoya** [comment]
Really, you are not declaring variables in the before (each) block so it is perfect. Nothing to add! 🙂

**Comment by vieiramanda11** [comment]
> Really, you are not declaring variables in the before (each) block so it is perfect. Nothing to add! slightly_smiling_face

Thank you @AndresFMoya. It's a good resource to have saved it for future tests.

**Comment by dev1980** [comment]
No comment from me.
